_wandb:
    value:
        cli_version: 0.21.3
        e:
            wu1jcsv3lprjoqszk07l2f4hs3oba34r:
                args:
                    - --file_url
                    - https://github.com/udacity/nd0821-c2-build-model-workflow-exercises/blob/master/lesson-2-data-exploration-and-preparation/exercises/exercise_4/starter/genres_mod.parquet?raw=true
                    - --artifact_name
                    - raw_data.parquet
                    - --artifact_type
                    - raw_data
                    - --artifact_description
                    - Data as downloaded
                codePath: download/download_data.py
                codePathLocal: download_data.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "18153803776"
                email: sstri005@gmail.com
                executable: /home/swstribling/miniconda3/envs/mlflow-c8796fcdf2a60e9d2d7a0e2de87ce7cf78fe7920/bin/python
                git:
                    commit: ee5fc53608e2fdccd5ea93475f29dea052c439cf
                    remote: https://github.com/SWStribling/genre_classification.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-d11f4501-b486-34d1-3572-89d479c703b3
                host: Maverick
                memory:
                    total: "16652648448"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/c/Users/sstri/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/download/download_data.py
                python: CPython 3.13.11
                root: /mnt/c/Users/sstri/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/download
                startedAt: "2025-12-16T20:45:21.651078Z"
                writerId: wu1jcsv3lprjoqszk07l2f4hs3oba34r
        m: []
        python_version: 3.13.11
        t:
            "3":
                - 2
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
