_wandb:
    value:
        cli_version: 0.21.3
        e:
            b4olaarixij2mzdj3jcesthcuc7uu8sk:
                args:
                    - --train_data
                    - data_train.csv:latest
                    - --model_config
                    - /mnt/c/Users/sstri/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/outputs/2025-12-16/15-00-55/random_forest_config.yml
                    - --export_artifact
                    - model_export
                    - --random_seed
                    - "42"
                    - --val_size
                    - "0.3"
                    - --stratify
                    - genre
                codePath: random_forest/run.py
                codePathLocal: run.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "19451072512"
                email: sstri005@gmail.com
                executable: /home/swstribling/miniconda3/envs/mlflow-a3629828cd971ffe646011f938d3373bb5d5ef95/bin/python
                git:
                    commit: acae67f52766c4809f1a722f566d963deeed975d
                    remote: https://github.com/SWStribling/genre_classification.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-d11f4501-b486-34d1-3572-89d479c703b3
                host: Maverick
                memory:
                    total: "16652648448"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /mnt/c/Users/sstri/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/random_forest/run.py
                python: CPython 3.13.11
                root: /mnt/c/Users/sstri/nd0821-c2-build-model-workflow-exercises/lesson-5-final-pipeline-release-and-deploy/exercises/exercise_14/starter/genre_classification/random_forest
                startedAt: "2025-12-16T21:04:03.639459Z"
                writerId: b4olaarixij2mzdj3jcesthcuc7uu8sk
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 62
            "4": 3.13.11
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
export_artifact:
    value: model_export
features:
    value:
        categorical:
            - time_signature
            - key
        nlp:
            - text_feature
        numerical:
            - danceability
            - energy
            - loudness
            - speechiness
            - acousticness
            - instrumentalness
            - liveness
            - valence
            - tempo
            - duration_ms
random_forest:
    value:
        bootstrap: true
        ccp_alpha: 0
        class_weight: balanced
        criterion: gini
        max_depth: 13
        max_features: null
        max_leaf_nodes: null
        max_samples: null
        min_impurity_decrease: 0
        min_samples_leaf: 1
        min_samples_split: 2
        min_weight_fraction_leaf: 0
        n_estimators: 100
        n_jobs: null
        oob_score: false
        random_state: 42
        verbose: 0
        warm_start: false
tfidf:
    value:
        max_features: 10
